package com.zephyr.studentsafe.bo;
// default package
// Generated 2010-9-14 23:25:58 by Hibernate Tools 3.2.2.GA


/**
 * Studenttimebook generated by hbm2java
 */
public class Studenttimebook implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String objUid;
	private String studentName;
	private java.util.Date time;
	private String event;
	private String rfidCardID;
	private Integer count;

	public String getRfidCardID() {
		return rfidCardID;
	}

	public void setRfidCardID(String rfidCardID) {
		this.rfidCardID = rfidCardID;
	}

	public Studenttimebook() {
	}

	public Studenttimebook(String objUid) {
		this.objUid = objUid;
	}

	
	public String getObjUid() {
		return this.objUid;
	}

	public void setObjUid(String objUid) {
		this.objUid = objUid;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public java.util.Date getTime() {
		return time;
	}

	public void setTime(java.util.Date time) {
		this.time = time;
	}

	public String getEvent() {
		return event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}


	

}
